### ISSUE TITLE
stderr output when checking for agent version

### ISSUE THREAD

**Issue by bp88** [circonus-labs/circonus-unified-agent#110]
If I try to check for the agent version `./sbin/circonus-unified-agentd --version`

I noticed that I get the following output:
>**2022/11/10 08:32:44 proto: duplicate proto type registered: k8s.io.apimachinery.pkg.api.resource.Quantity**
>circonus-unified-agent 0.2.0 (git: master 0483f4a v0.2.0) built:2022-11-09T20:00:39Z

After digging deeper, I noticed that it seems that the first line (what is bolded) is actually stderr that is being displayed. Would it be possible to not show stderr particularly when simply checking the agent version? It's possible this shows up when trying to call other flags as well.

**Comment by wkrause13** [comment]
Thanks @bp88 for pointing this out, we tracked down the source of this stderr message and removed it. The fix should be included in the next release.
